vorUmfrage:
    pattern: /
    defaults: { _controller: ChrisDissWebsiteBundle:Website:vorUmfrage }

codeForm:
    pattern:  /fe
    defaults: { _controller: ChrisDissWebsiteBundle:Website:codeForm }

instructions:
    pattern:  /anleitung
    defaults: { _controller: ChrisDissWebsiteBundle:Website:instructions }

dryRun:
    pattern:  /uebungsaufgaben
    defaults: { _controller: ChrisDissWebsiteBundle:Website:dryRun }

testung:
    pattern:  /testung
    defaults: { _controller: ChrisDissWebsiteBundle:Website:test }

saveResult:
    pattern:  /save-result
    defaults: { _controller: ChrisDissWebsiteBundle:Website:saveResult }
