initialInstructions:
    pattern:  /
    defaults: { _controller: ChrisDissWebsiteBundle:Website:initialInstructions }

dryRun:
    pattern:  /uebungsaufgaben
    defaults: { _controller: ChrisDissWebsiteBundle:Website:dryRun }
